config/routes.rb
PlayByNumbers::Application.routes.draw do

  root 'plays#index'

  resources :plays, only: [:index, :show]

end

app/models/act.rb
class Act < ActiveRecord::Base

  validates :title, presence: true, uniqueness: { scope: :play_id }
  validates :play, presence: true

  belongs_to :play, inverse_of: :acts
  has_many :scenes, inverse_of: :act, dependent: :destroy

end

app/models/line.rb
class Line < ActiveRecord::Base

  validates :line_text, presence: true
  validates :speech, presence: true

  belongs_to :speech, inverse_of: :lines, counter_cache: true

end

app/models/play.rb
class Play < ActiveRecord::Base

  validates :title, presence: true, uniqueness: true

  has_many :speakers, inverse_of: :play, dependent: :destroy
  has_many :acts, inverse_of: :play, dependent: :destroy
  has_many :scenes, through: :acts

end

app/models/scene.rb
class Scene < ActiveRecord::Base

  validates :title, presence: true, uniqueness: { scope: :act_id }
  validates :act, presence: true

  belongs_to :act, inverse_of: :scenes
  has_many :speeches, inverse_of: :scene, dependent: :destroy
  has_many :speakers, -> { distinct }, through: :speeches

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { scope: :play_id }
  validates :play, presence: true

  belongs_to :play, inverse_of: :acts
  has_many :speeches, inverse_of: :speaker, dependent: :destroy
  has_many :scenes, -> { distinct }, through: :speeches
  has_many :lines, through: :speeches

  def num_lines
    @num_lines ||= lines.count
  end

  def longest_speech_lines
    @speech ||= longest_speech
    @speech.nil? ? 0 : @speech.lines_count
  end

  def num_scenes
    @num_scenes ||= scenes.count
  end

  def self.sort_speakers(params)
    speakers = Speaker.where(play_id: params[:id])

    params[:direction] ||= 'desc'
    order = (params[:direction] == 'asc') ? 1 : -1

    if params[:sort] == 'longest_speech'
      speakers.sort_by { |speaker| order * speaker.longest_speech_lines }
    elsif params[:sort] == 'num_scenes'
      speakers.sort_by { |speaker| order * speaker.num_scenes }
    elsif params[:sort] == 'percent_scenes'
      speakers.sort_by { |speaker| order * speaker.num_scenes }
    else
      params[:sort] ||= 'num_lines'
      speakers.sort_by { |speaker| order * speaker.num_lines }
    end
  end

  private

  def longest_speech
    if speeches.empty?
      nil
    else
      speeches.order(lines_count: :desc).limit(1).first
    end
  end

end

app/models/speech.rb
class Speech < ActiveRecord::Base

  validates :speaker, presence: true
  validates :scene, presence: true

  belongs_to :speaker, inverse_of: :speeches
  belongs_to :scene, inverse_of: :speeches
  has_many :lines, inverse_of: :speech, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  def index
    @plays = Play.all
  end

  def show
    @play = Play.find(params[:id])
    @speakers = Speaker.sort_speakers(params)[0..9]
    @total_scenes = @play.scenes.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def column_sort(column_title, method_name)
    direction = (params[:sort] == method_name && params[:direction] == "desc") ? "asc" : "desc"
    link_to column_title, sort: method_name, direction: direction
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Play by Numbers" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="page-content">
      <div class="row">
        <div class="small-12 columns">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/plays/_speakers.html.erb
<table>
  <thead>
    <th width="200"></th>
    <th><%= column_sort 'Number of Lines', 'num_lines' %></th>
    <th><%= column_sort 'Longest Speech', 'longest_speech' %></th>
    <th><%= column_sort 'Number of Scenes', 'num_scenes' %></th>
    <th><%= column_sort 'Percentage of Scenes', 'percent_scenes' %></th>
  </thead>
  <tbody>
    <% @speakers.each do |speaker| %>
      <tr>
        <td><%= speaker.name %></td>
        <td><%= speaker.num_lines %></td>
        <td><%= speaker.longest_speech_lines %></td>
        <td><%= speaker.num_scenes %></td>
        <td><%= ((speaker.num_scenes * 100.0) / @total_scenes).round %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plays/index.html.erb
<h1>All Plays</h1>

<div id="play-list">
  <% @plays.each do |play| %>
    <p><%= link_to play.title, play_path(play) %></p>
  <% end %>
</div>

app/views/plays/show.html.erb
<h1><%= @play.title %></h1>

<div id="speakers"><%= render 'speakers' %></div>

<p><%= link_to 'Back to All Plays', plays_path %></p>

app/views/plays/show.js.erb
$('#speakers').html('<%= escape_javascript(render 'speakers') %>');